project_id = "ehqspernqapvxiijjkuk"

[functions.preflight]
verify_jwt = false

[functions.eta]
verify_jwt = false

[functions.campaigns-start]
verify_jwt = false

[functions.dispatcher]
verify_jwt = false

[functions."sync-phone-numbers"]
verify_jwt = true

[functions."webhooks-whatsapp"]
verify_jwt = false
