// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehqspernqapvxiijjkuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVocXNwZXJucWFwdnhpaWpqa3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODI3OTksImV4cCI6MjA3MDQ1ODc5OX0.aOuSSX49evZyvRCtotzF5K3jJi1VviXW077ury5l0RU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});